name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22  # or your installed version

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build ./...

    - name: Run tests
      run: go test ./... -v
